# Generated by Django 3.1.5 on 2021-02-03 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPX_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpx_name', models.TextField(help_text='The raw gpx file name')),
                ('gpx_file', models.FileField(blank=True, max_length=511, null=True, upload_to='uploads/gpx/', verbose_name='GPX Track')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mp', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.CharField(max_length=50)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.ruta')),
            ],
        ),
    ]
