# Generated by Django 3.1.5 on 2021-02-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_gpx_file_punto_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='KML_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_name', models.TextField(help_text='The raw kml file name')),
                ('kml_file', models.FileField(blank=True, max_length=511, null=True, upload_to='uploads/kml/', verbose_name='KML track')),
            ],
        ),
    ]
