# Generated by Django 3.1.6 on 2021-02-16 13:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPX_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpx_name', models.TextField(help_text='The raw gpx file name')),
                ('gpx_file', models.FileField(blank=True, max_length=511, null=True, upload_to='uploads/gpx/', verbose_name='GPX File')),
            ],
        ),
        migrations.CreateModel(
            name='GPX_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('mlstring', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='GPX_waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KML_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_name', models.TextField(help_text='The raw kml file name')),
                ('kml_file', models.FileField(blank=True, max_length=511, null=True, upload_to='uploads/kml/', verbose_name='KML File')),
            ],
        ),
        migrations.CreateModel(
            name='KML_lstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lstring', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='GPX_trackpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('ele', models.FloatField()),
                ('time', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacentre.gpx_track')),
            ],
        ),
    ]
