# Generated by Django 3.1.6 on 2021-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
