# Generated by Django 3.1.6 on 2021-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpx_waypoint',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gpx_trackpoint',
            name='ele',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpx_trackpoint',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gpx_waypoint',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpx_waypoint',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
