# Generated by Django 3.1.6 on 2021-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0002_auto_20210308_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpx_track',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gpx_track',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
