# Generated by Django 3.1.6 on 2021-05-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0002_sensor_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='units',
        ),
    ]
