# Generated by Django 3.1.6 on 2022-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0003_remove_measurement_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='avg_velocity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='delay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='velocity',
            field=models.FloatField(null=True),
        ),
    ]
