# Generated by Django 3.1.6 on 2021-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0004_kml_lstring_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpx_track',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kml_lstring',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
