# Generated by Django 3.1.6 on 2021-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0006_measurement_sck_device_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
