# Generated by Django 3.1.6 on 2021-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0007_sensor_sensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sck_device',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.AlterField(
            model_name='sck_device',
            name='sck_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
