# Generated by Django 3.1.6 on 2021-04-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0008_auto_20210412_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
