# Generated by Django 3.1.6 on 2021-04-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0009_auto_20210412_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='device',
        ),
        migrations.AddField(
            model_name='gpx_track',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacentre.sck_device'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='datacentre.sck_device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
