# Generated by Django 3.1.6 on 2021-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0010_auto_20210413_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('zoom', models.FloatField()),
                ('devices', models.ManyToManyField(to='datacentre.SCK_device')),
            ],
        ),
    ]
