# Generated by Django 3.1.6 on 2021-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0011_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
