# Generated by Django 3.1.6 on 2021-05-20 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0012_config_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dtour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(null=True)),
                ('ratio', models.FloatField(null=True)),
                ('mlstring', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacentre.gpx_track')),
            ],
        ),
    ]
