# Generated by Django 3.1.6 on 2021-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0013_dtour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtour',
            old_name='length',
            new_name='distance',
        ),
    ]
